# Generated by Django 5.1.6 on 2025-02-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_expense_category_expense_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=255),
        ),
    ]
