# Generated by Django 5.1.6 on 2025-02-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
