# Generated by Django 5.1.6 on 2025-02-27 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_employee_role_attendance_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
